root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main cmd/gitops/main.go"
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor","node_modules", ".garden","ui","test","tools","dist","bin",".git",".parcel-cache"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "./tmp/main ui run"
  include_dir = ["cmd","pkg","manifests","api"]
  include_ext = ["go","html","js"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
